photos = [

  {'name': 'Georgetown Harbor', 'file': 'DSC_0409.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/eLL5a-georgetown-harbor-full-resolution/buy', 'token': 'eLL5a'}},
  {'name': 'DC from the Key Bridge', 'file': 'DSC_0611.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/V47xX-dc-from-the-key-bridge-full-resolution/buy', 'token': 'V47xX'}},
  {'name': 'Red Door', 'file': 'DSC_0649.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/gg5FY-red-door-full-resolution/buy', 'token': 'gg5FY'}},
  {'name': 'The Look', 'file': 'DSC_0655.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/C4120-the-look-full-resolution/buy', 'token': 'C4120'}},
  {'name': '', 'file': 'DSC_0681.jpg', 'shoplocket': {'link': '', 'token': ''}},
  {'name': 'Westminster Abbey', 'file': 'DSC_0843.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/UoHhG-westminster-abbey-full-resolution/buy', 'token': 'UoHhG'}},
  {'name': 'Cassis Boats', 'file': 'DSC_1014.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/CL9fU-cassis-boats-full-resolution/buy', 'token': 'CL9fU'}},
  {'name': 'Cote d&rsquo;Azur', 'file': 'DSC_1051.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/74a0k-cote-d-azur-full-resolution/buy', 'token': '74a0k'}},
  {'name': 'Party in Aix', 'file': 'DSC_1084.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/vC3hR-party-in-aix-full-resolution/buy', 'token': 'vC3hR'}},
  {'name': 'Campagne Provencale', 'file': 'DSC_1198.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/mRJuF-campagne-provencale-full-resolution/buy', 'token': 'mRJuF'}},
  {'name': 'Quelque Chose Pour Manger', 'file': 'DSC_1214.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/wFySD-quelque-chose-pour-manger-full-resolution/buy', 'token': 'wFySD'}},
  {'name': 'The Road to Provence', 'file': 'DSC_1373.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/nRQuG-the-road-to-provence-full-resolution/buy', 'token': 'nRQuG'}},
  {'name': 'Lavande', 'file': 'DSC_1606.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/5cay1-lavande-full-resolution/buy', 'token': '5cay1'}},
  {'name': 'The Road Ahead', 'file': 'DSC_1617.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/Qnc7x-the-road-ahead-full-resolution/buy', 'token': 'Qnc7x'}},
  {'name': 'St. Tropez', 'file': 'DSC_1818.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/yXNl0-st-tropez-full-resolution/buy', 'token': 'yXNl0'}},
  {'name': 'Down in the Bar', 'file': 'DSC_2005.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/U0bAb-down-in-the-bar-full-resolution/buy', 'token': 'U0bAb'}},
  {'name': 'Virgil&rsquo;s BBQ', 'file': 'DSC_2177.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/rXIcd-virgil-s-bbq-full-resolution/buy', 'token': 'rXIcd'}},
  {'name': 'Happy Banjo Playing', 'file': 'DSC_2468.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/zcGgh-happy-banjo-playing-full-resolution/buy', 'token': 'zcGgh'}},
  {'name': 'Old Rag', 'file': 'DSC_2576.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/oiNi1-old-rag-full-resolution/buy', 'token': 'oiNi1'}},
  {'name': 'Fallingwater', 'file': 'DSC_2748.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/x2f7J-fallingwater-full-resolution/buy', 'token': 'x2f7J'}},
  {'name': 'Potomac Kayaks', 'file': 'DSC_2843.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/XGWZI-potomac-kayaks-full-resolution/buy', 'token': 'XGWZI'}},
  {'name': 'Under the Key Bridge', 'file': 'DSC_2966.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/5NkWv-under-the-key-bridge-full-resolution/buy', 'token': '5NkWv'}},
  {'name': 'NYC Lights', 'file': 'DSC_3025.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/0FFNI-nyc-lights-full-resolution/buy', 'token': '0FFNI'}},
  {'name': 'Scar', 'file': 'DSC_3481.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/Nv2bw-scar-full-resolution/buy', 'token': 'Nv2bw'}},
  {'name': 'Old and New in Abu Dhabi', 'file': 'DSC_3524.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/LVvi4-old-and-new-in-abu-dhabi-full-resolution/buy', 'token': 'LVvi4'}},
  {'name': 'Half Moon Bay', 'file': 'DSC_3687.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/1MuIn-half-moon-bay-full-resolution/buy', 'token': '1MuIn'}},
  {'name': 'Golden Gate Sunset', 'file': 'DSC_3782.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/mN86l-golden-gate-sunset-full-resolution/buy', 'token': 'mN86l'}},
  {'name': 'Napa Lemons', 'file': 'DSC_3838.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/ab0z5-napa-lemons-full-resolution/buy', 'token': 'ab0z5'}},
  {'name': 'Life on the Coast', 'file': 'DSC_3887.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/SIy6u-life-on-the-coast-full-resolution/buy', 'token': 'SIy6u'}},
  {'name': 'Surfer&rsquo;s Paradise', 'file': 'DSC_3920.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/haSY7-surfer-s-paradise-full-resolution/buy', 'token': 'haSY7'}},
  {'name': 'Twin Peaks Sunset', 'file': 'DSC_4005.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/priSa-twin-peaks-sunset-full-resolution/buy', 'token': 'priSa'}},
  {'name': 'Golden Gate Night', 'file': 'DSC_4011.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/fNzcV-golden-gate-night-full-resolution/buy', 'token': 'fNzcV'}},
  {'name': 'Pan on Pipes', 'file': 'DSC_4042.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/6T6vX-pan-on-pipes-full-resolution/buy', 'token': '6T6vX'}},
  {'name': 'California Coast', 'file': 'DSC_4084.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/03PIf-california-coast-full-resolution/buy', 'token': '03PIf'}},
  {'name': 'Noe Valley', 'file': 'DSC_4170.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/hN83M-noe-valley-full-resolution/buy', 'token': 'hN83M'}},
  {'name': 'Ocean Beach', 'file': 'DSC_4267.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/q8H4d-ocean-beach-full-resolution/buy', 'token': 'q8H4d'}},
  {'name': 'Hephaestus', 'file': 'DSC_4283.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/yyh2E-hephaestus-full-resolution/buy', 'token': 'yyh2E'}},
  {'name': 'Eastern Foothills', 'file': 'DSC_4346.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/qHtI5-eastern-foothills-full-resolution/buy', 'token': 'qHtI5'}},
  {'name': 'Among Giants', 'file': 'DSC_4454.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/Q6dZa-among-giants-full-resolution/buy', 'token': 'Q6dZa'}},
  {'name': '', 'file': 'DSC_4536.jpg', 'shoplocket': {'link': '', 'token': ''}},
  {'name': 'Napa Valley Vineyards', 'file': 'DSC_4551.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/DnpyB-napa-valley-vineyards-full-resolution/buy', 'token': 'DnpyB'}},
  {'name': 'Napa Valley Sunset', 'file': 'DSC_4597.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/KsOMJ-napa-valley-sunset-full-resolution/buy', 'token': 'KsOMJ'}},
  {'name': 'Reflections in San Francisco', 'file': 'DSC_4606.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/duAdE-reflections-in-san-francisco-full-resolution/buy', 'token': 'duAdE'}},
  {'name': 'Japanese Garden', 'file': 'DSC_5013.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/ZNq09-japanese-garden-full-resolution/buy', 'token': 'ZNq09'}},
  {'name': 'Dolores Park', 'file': 'DSC_5024.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/sWlj3-dolores-park-full-resolution/buy', 'token': 'sWlj3'}},
  {'name': 'Yosemite', 'file': 'DSC_5074.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/xZESI-yosemite-full-resolution/buy', 'token': 'xZESI'}},
  {'name': '', 'file': 'DSC_5137.jpg', 'shoplocket': {'link': '', 'token': ''}},
  {'name': 'Buena Vista', 'file': 'DSC_5343.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/hM6Rv-buena-vista-full-resolution/buy', 'token': 'hM6Rv'}},
  {'name': 'Big Sky', 'file': 'DSC_5487.jpg', 'shoplocket': {'link': 'http://www.shoplocket.com/products/FSWzy-big-sky-full-resolution/buy', 'token': 'FSWzy'}},
  {'name': 'Rays Over Glacier', 'file': 'DSC_5498.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/aCZEl-rays-over-glacier-full-resolution/buy', 'token': 'aCZEl'}},
  {'name': 'Pixie Dust', 'file': 'DSC_5516.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/yMee0-pixie-dust-full-resolution/buy', 'token': 'yMee0'}},
  {'name': 'Mountain Mirror', 'file': 'DSC_5650.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/670Va-mountain-mirror-full-resolution/buy', 'token': '670Va'}},
  {'name': 'Night Sky', 'file': 'DSC_5657.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/eZpud-night-sky-full-resolution/buy', 'token': 'eZpud'}},
  {'name': 'Montana Mountains', 'file': 'DSC_5663.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/emJKo-montana-mountains-full-resolution/buy', 'token': 'emJKo'}},
  {'name': 'Sky on Fire', 'file': 'DSC_5932.jpg', 'shoplocket': {'link': 'httpss://www.shoplocket.com/products/WoSLs-sky-on-fire-full-resolution/buy', 'token': 'WoSLs'}},
  {'name': 'Shed', 'file': 'DSCF8239.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/BSfCU-shed-full-resolution/buy', 'token': 'BSfCU'}},
  {'name': '', 'file': 'P1040462.jpg', 'shoplocket': {'link': '', 'token': ''}},
  {'name': 'Marrakech Sunset', 'file': 'P1050586.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/dyg97-marrakech-sunset-full-resolution/buy', 'token': 'dyg97'}},
  {'name': 'Magic Lamps', 'file': 'P1050793.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/fEA0y-magic-lamps-full-resolution/buy', 'token': 'fEA0y'}},
  {'name': 'Les Dents du Midi', 'file': 'P1060031.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/90iFp-les-dents-du-midi-full-resolution/buy', 'token': '90iFp'}},
  {'name': 'Neapolitan Chapel', 'file': 'P1060724.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/iwGKJ-neapolitan-chapel-full-resolution/buy', 'token': 'iwGKJ'}},
  {'name': 'When in Rome', 'file': 'P1060725.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/ucaGk-when-in-rome-full-resolution/buy', 'token': 'ucaGk'}},
  {'name': 'Neapolitan Courtyard', 'file': 'P1070015.jpg', 'shoplocket': {'link': 'https://www.shoplocket.com/products/76TrA-neapolitan-courtyard-full-resolution/buy', 'token': '76TrA'}}

];
